services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rha_db
      POSTGRES_USER: rha_user
      POSTGRES_PASSWORD: rha_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rha_user -d rha_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://rha_user:rha_password@db:5432/rha_db
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@rha.local
      DJANGO_SUPERUSER_PASSWORD: admin123
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
  media_volume:
  static_volume:
