# Generated by Django 6.0.6 on 2026-06-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-created_at'], 'verbose_name': 'Congé', 'verbose_name_plural': 'Congés'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name'], 'verbose_name': 'Type de congé', 'verbose_name_plural': 'Types de congés'},
        ),
    ]
