# Generated by Django 6.0.6 on 2026-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Bulletin de paie', 'verbose_name_plural': 'Bulletins de paie'},
        ),
        migrations.AddField(
            model_name='payslip',
            name='currency',
            field=models.CharField(choices=[('CDF', 'CDF (Franc Congolais)'), ('XOF', 'XOF (Franc CFA)'), ('USD', 'USD (Dollar Américain)')], default='CDF', max_length=3),
        ),
    ]
