# Generated by Django 6.0.6 on 2026-06-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payslip_options_payslip_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='cnss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payslip',
            name='cnss_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
