# Generated by Django 6.0.6 on 2026-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cnss_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro CNSS'),
        ),
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.CharField(choices=[('CDF', 'CDF (Franc Congolais)'), ('XOF', 'XOF (Franc CFA)'), ('USD', 'USD (Dollar Américain)')], default='CDF', max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('prestation', 'Prestation de services')], default='cdi', max_length=20),
        ),
    ]
