# Generated by Django 6.0.6 on 2026-06-15 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_cnss_number_employee_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('prestation', 'Prestation de services')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('CDF', 'CDF (Franc Congolais)'), ('XOF', 'XOF (Franc CFA)'), ('USD', 'USD (Dollar Américain)')], default='CDF', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('terminated', 'Résilié')], default='active', max_length=20)),
                ('signed_copy', models.FileField(blank=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-created_at'],
            },
        ),
    ]
