# Generated by Django 6.0.6 on 2026-06-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-created_at'], 'verbose_name': "Offre d'emploi", 'verbose_name_plural': "Offres d'emploi"},
        ),
    ]
